//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurmanRybApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOff
    {
        public int PositionId { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateOff { get; set; }
    
        public virtual Assortiment Assortiment { get; set; }
    }
}
